name: Remove old artifacts

on:
  workflow_dispatch: {}
  # schedule:
    # Every day at 4am
    # - cron: '0 4 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: 1 minute
        skip-recent: 2
        skip-tags: false
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
